# MACHO-GPT v3.4-mini 멀티 그룹 WhatsApp 스크래핑 설정
# Samsung C&T Logistics · HVDC Project

whatsapp_groups:
  - name: "MR.CHA 전용"
    save_file: "data/messages_mr_cha.json"
    scrape_interval: 60
    priority: "HIGH"

  - name: "ADNOC Berth Coordination"
    save_file: "data/messages_adnoc_berth.json"
    scrape_interval: 120
    priority: "MEDIUM"

  - name: "Logistics Team"
    save_file: "data/messages_logistics.json"
    scrape_interval: 90
    priority: "MEDIUM"

scraper_settings:
  chrome_data_dir: "chrome-data"
  headless: true
  timeout: 30000
  max_parallel_groups: 5

ai_integration:
  enabled: true
  summarize_on_extraction: true
  confidence_threshold: 0.90

apify_fallback:
  enabled: false  # 원격 폴백을 사용할 경우 true로 설정
  apify_actor_id: ""  # 예: "user/whatsapp-scraper"
  apify_token_env: "APIFY_TOKEN"  # .env에 저장된 토큰 키
  input_overrides: {}
  timeout_seconds: 120

